# Generated by Django 4.2.5 on 2023-11-16 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('filled_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('desc', models.TextField()),
                ('id', models.AutoField(default=404, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='signinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('uname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='unregisteredContact',
            fields=[
                ('name1', models.CharField(max_length=30)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=10)),
                ('filled_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('desc1', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
