# Generated by Django 4.2.5 on 2023-11-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
